# Generated by Django 6.0.2 on 2026-02-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(max_length=124, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=124, verbose_name='Фамилия пользователя')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватарка пользователя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Github')),
                ('about', models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание профиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
