# Generated by Django 5.2.4 on 2026-03-12 14:35

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, help_text='Форматы: 8XXXXXXXXXX, либо +7XXXXXXXXXX. X — цифры.', max_length=256, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, help_text='Формат: https://github.com/username', null=True, unique=True, verbose_name='Ссылка на Github'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=124, validators=[users.validators.validate_no_digits], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Форматы: 8XXXXXXXXXX, либо +7XXXXXXXXXX', max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=124, validators=[users.validators.validate_no_digits], verbose_name='Фамилия пользователя'),
        ),
    ]
