# Generated by Django 6.0.2 on 2026-02-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(max_length=124, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=124, verbose_name='Фамилия пользователя')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватарка пользователя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Github')),
                ('about', models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание профиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания проекта')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Github')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6, verbose_name='Статус проекта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
