# Generated by Django 5.2.4 on 2026-03-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Укажите полную ссылку на репозиторий, например: https://github.com/username/repository', null=True, unique=True, verbose_name='Ссылка на Github'),
        ),
    ]
